services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    environment:
      POSTGRES_USER : username
      POSTGRES_PASSWORD : password
      PGDATA : /var/lib/postgres/data
      POSTGRES_DB: book_social_network
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - postgres: /data/postgres
    networks:
      - spring-demo
  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025



volumes:
  postgres:
    driver: local

networks:
  spring-demo:
    driver: bridge